[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
rpc_endpoints={sepolia-eth="${SEPOLIA_RPC_URL}", arb-sepolia="${ZKSYNC_SEPOLIA_RPC_URL}"}


remappings = ["@openzeppelin/=lib/openzeppelin-contracts/",
"@ccip/=lib/ccip",
"@chainlink/local/=lib/chainlink-local/"
]
